---
author: 'Michael Andrew Barrowman'
date: '`r format(Sys.time(), "%B %Y")`'
institution: 'University of Manchester'
division: 'Division of Informatics, Imaging and Data Science'
advisor: 'Dr. Matthew Sperrin, Prof. Niels Peek, Dr. Glen Martin, Dr. Mark Lambie'
# If you have more two advisors, un-silence line 7
#altadvisor: ''
department: 'School of Health Sciences'
degree: 'PhD Medicine'
title: 'Multi-State Clinical Prediction Models in Renal Replacement Therapy'
knit: mpipe::MyRender
#knit: bookdown::render_book
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    includes:
      in_header: "hypothesis.html"
    config:
      toc:
        collapse: section
  thesisdown::thesis_pdf: 
    includes:
      in_header: header.tex
#  thesisdown::thesis_word: default
#  thesisdown::thesis_epub: default
# If you are creating a PDF you'll need to write your preliminary content (e.g., abstract, acknowledgements) here or
# use code similar to line 22-23 for the .RMD files. If you are NOT producing a PDF, you can delete or silence lines 21-32 in this YAML header.
abstract: |
  `r {source("prelim_Subsection.R");prelim_Subsection("all","abstract")}`
# If you'd rather include the preliminary content in files instead of inline
# like below, use a command like that for the abstract above.  Note that a tab is 
# needed on the line after the `|`.
acknowledgements: |
  `r {source("prelim_Subsection.R");prelim_Subsection("all","acknowledgements")}`
# Specify the location of the bibliography below
bibliography: ["bib/thesis.bib","bib/MyCites.bib"]
biblio-style: "ieee"
link-citations: true
# Download your specific csl file and refer to it in the line below.
csl: csl/ieee.csl #https://github.com/citation-style-language/styles
lot: true
lof: true
# If you prefer blank lines between paragraphs, un-silence lines  40-41 (this requires package tikz)
header-includes:
#- \usepackage{tikz}
- \usepackage{amsmath}
- \usepackage[T1]{fontenc}
- \usepackage{rotating}
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage{xcolor}
- \usepackage{geometry}
---


```{r include_packages, include = FALSE}
source("setup.R")
```

  
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>

`r fb(gitbook=readLines("header.tex"))`

# Introduction {-}

<!--
To Do List:
Set up Supervisor's Hypothesis Accounts
Sort out monospacing in kables (double spaces get rendered as single space. Seems to be happening                                   before being saved as a html)
Add in written details in Supp. Material
Figure out scroll_box() for the PH Five-State
Make equations not in aligns (rolls onto second page in Five-State Model)
Write up current draft of other papers
pdf tables aren't aligned
Add Timeline
Figure out equation referencing
Download options showing up in pdf
Abstract subsections appearing in TOC in Thesis (e.g. 3.0.1 Background)
Add "Appendix" heading (or page) to thesis version

-->

Welcome to my Thesis. I've used R Markdown to create a gitbook style thesis, as well as a traditional pdf (following the UoM Thesis template).
  
I sent an email with details of how you can log in to the [hypothes.is](https://hypothes.is/) system. This will let you add comments to the gitbook pages. This is actually a really useful tool and has the ability to add annotations to any webpage. Just highlight the text you want to comment on, and the annotate bubble pops up. Make sure you click Post to Public after writing the annotation and annotations.

Google Docs was great, but when I started to use R Markdown, I realised I could embed tables and equations automatically using `kable` and `LaTeX` and it'll would make it much easier to collate papers into my thesis. Google Docs on it's own became rather clunky (especially with tables, just like Word) and whenever I updated a document using R Markdown, any comments that were added to the document were lost. It was also difficult for you to remember *where* each document lived. Gitbook solves these problems.


I've written this document to be ready to become my thesis, but each chapter is a separate file, which can be downloaded within the chapter as a pdf or a a raw tex file (including relevant supplementary material). 



Everything here is hosted in a [Github repo](https://https://github.com/MyKo101/Thesis). I originally used Github as my backup, but then decided to increase how I used it.


I've also outlined my expected timeline below. This thesis document, along with each chapter's files (at their respective urls) will be updated.

`r fb(gitbook="## Abstract {-}")`

`r {source("prelim_Subsection.R");prelim_Subsection("html","abstract")}`

